In [1]:
import pandas as pd 
import numpy as np 
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

# Loading dataset

In [2]:
url = 'https://raw.githubusercontent.com/selva86/datasets/master/Sonar.csv'

df = pd.read_csv(url,header=None,skiprows=1)
df.head(5)

,0,1,2,3,4,5,6,7,8,9,...,51,52,53,54,55,56,57,58,59,60
0,0.0200,0.0371,0.0428,0.0207,0.0954,0.0986,0.1539,0.1601,0.3109,0.2111,...,0.0027,0.0065,0.0159,0.0072,0.0167,0.0180,0.0084,0.0090,0.0032,1
1,0.0453,0.0523,0.0843,0.0689,0.1183,0.2583,0.2156,0.3481,0.3337,0.2872,...,0.0084,0.0089,0.0048,0.0094,0.0191,0.0140,0.0049,0.0052,0.0044,1
2,0.0262,0.0582,0.1099,0.1083,0.0974,0.2280,0.2431,0.3771,0.5598,0.6194,...,0.0232,0.0166,0.0095,0.0180,0.0244,0.0316,0.0164,0.0095,0.0078,1
3,0.0100,0.0171,0.0623,0.0205,0.0205,0.0368,0.1098,0.1276,0.0598,0.1264,...,0.0121,0.0036,0.0150,0.0085,0.0073,0.0050,0.0044,0.0040,0.0117,1
4,0.0762,0.0666,0.0481,0.0394,0.0590,0.0649,0.1209,0.2467,0.3564,0.4459,...,0.0031,0.0054,0.0105,0.0110,0.0015,0.0072,0.0048,0.0107,0.0094,1

In [3]:
df.shape

(208, 61)

In [4]:
df.describe()

,0,1,2,3,4,5,6,7,8,9,...,51,52,53,54,55,56,57,58,59,60
count,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,...,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000
mean,0.029164,0.038437,0.043832,0.053892,0.075202,0.104570,0.121747,0.134799,0.178003,0.208259,...,0.013420,0.010709,0.010941,0.009290,0.008222,0.007820,0.007949,0.007941,0.006507,0.466346
std,0.022991,0.032960,0.038428,0.046528,0.055552,0.059105,0.061788,0.085152,0.118387,0.134416,...,0.009634,0.007060,0.007301,0.007088,0.005736,0.005785,0.006470,0.006181,0.005031,0.500070
min,0.001500,0.000600,0.001500,0.005800,0.006700,0.010200,0.003300,0.005500,0.007500,0.011300,...,0.000800,0.000500,0.001000,0.000600,0.000400,0.000300,0.000300,0.000100,0.000600,0.000000
25%,0.013350,0.016450,0.018950,0.024375,0.038050,0.067025,0.080900,0.080425,0.097025,0.111275,...,0.007275,0.005075,0.005375,0.004150,0.004400,0.003700,0.003600,0.003675,0.003100,0.000000
50%,0.022800,0.030800,0.034300,0.044050,0.062500,0.092150,0.106950,0.112100,0.152250,0.182400,...,0.011400,0.009550,0.009300,0.007500,0.006850,0.005950,0.005800,0.006400,0.005300,0.000000
75%,0.035550,0.047950,0.057950,0.064500,0.100275,0.134125,0.154000,0.169600,0.233425,0.268700,...,0.016725,0.014900,0.014500,0.012100,0.010575,0.010425,0.010350,0.010325,0.008525,1.000000
max,0.137100,0.233900,0.305900,0.426400,0.401000,0.382300,0.372900,0.459000,0.682800,0.710600,...,0.070900,0.039000,0.035200,0.044700,0.039400,0.035500,0.044000,0.036400,0.043900,1.000000

In [5]:
# df.sample(1)

In [6]:
df[60].value_counts()

0    111
1     97
Name: 60, dtype: int64

In [7]:
df.groupby(60).mean()

,0,1,2,3,4,5,6,7,8,9,...,50,51,52,53,54,55,56,57,58,59
60,,,,,,,,,,,,,,,,,,,,,
0,0.034989,0.045544,0.050720,0.064768,0.086715,0.111864,0.128359,0.149832,0.213492,0.251022,...,0.019352,0.016014,0.011643,0.012185,0.009923,0.008914,0.007825,0.009060,0.008695,0.006930
1,0.022498,0.030303,0.035951,0.041447,0.062028,0.096224,0.114180,0.117596,0.137392,0.159325,...,0.012311,0.010453,0.009640,0.009518,0.008567,0.007430,0.007814,0.006677,0.007078,0.006024

In [8]:
# Separating X and y
X = df.iloc[:, :-1]
y =  df.iloc[:, -1]

In [9]:
X_train , X_test ,y_train ,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

print(X_train.shape , X_test.shape ,X.shape)

(166, 60) (42, 60) (208, 60)

In [10]:
model = LogisticRegression()

In [11]:
model.fit(X_train,y_train)
# accuracy on training data 
X_train_pred = model.predict(X_train)
train_data_accuracy = accuracy_score(X_train_pred,y_train)
train_data_accuracy

0.8373493975903614

In [12]:
# accuracy on testing data 
X_test_pred = model.predict(X_test)
Test_data_accuracy = accuracy_score(X_test_pred,y_test)
Test_data_accuracy

0.7857142857142857

In [13]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(model,X,y,cv=5,scoring="accuracy")
scores.mean()

0.6300813008130082

# Making a predictive system

In [14]:
import numpy as np

# 1. Complete tuple containing all 60 features
input_data = (
    0.0286,
    0.0453,
    0.0277,
    0.0174,
    0.0384,
    0.0990,
    0.1201,
    0.1833,
    0.2105,
    0.3039,
    0.2988,
    0.4250,
    0.6343,
    0.8198,
    1.0000,
    0.9988,
    0.9508,
    0.9025,
    0.7234,
    0.5122,
    0.2074,
    0.3985,
    0.5890,
    0.2872,
    0.0361,
    0.1205,
    0.2705,
    0.3472,
    0.3680,
    0.3533,
    0.1076,
    0.1223,
    0.1884,
    0.1908,
    0.2570,
    0.2890,
    0.2872,
    0.4910,
    0.5955,
    0.3663,
    0.1860,
    0.2785,
    0.2227,
    0.1340,
    0.1118,
    0.0123,
    0.0503,
    0.0326,
    0.0081,
    0.0039,
    0.0014,
    0.0045,
    0.0014,
    0.0038,
    0.0013,
    0.0008,
    0.0037,
    0.0020,
    0.0021,
    0.0015,
)

# 2. Convert to numpy array & reshape to (1, 60)
input_data_as_numpy_array = np.asarray(input_data)
input_data_reshaped = input_data_as_numpy_array.reshape(1, -1)

# 3. Predict
prediction = model.predict(input_data_reshaped)
print(prediction)

if prediction[0] == "R":
    print("The object is a Rock")
else:
    print("The object is a Mine")

[1]
The object is a Mine

In [15]:
import pickle

with open("model.pkl", "wb") as file:
    pickle.dump(model, file)

print("Model saved successfully!")

Model saved successfully!