# Text Preprocessing in NLP Assignment

In [7]:
import pandas as pd

In [8]:
import json
import pandas as pd

with open("top_rated.json", "r", encoding="utf-8") as f:
    data = json.load(f)

movies = data["results"]

df = pd.DataFrame(movies)

print(df.columns)

Index(['adult', 'backdrop_path', 'genre_ids', 'id', 'title',
       'original_language', 'original_title', 'overview', 'popularity',
       'poster_path', 'release_date', 'softcore', 'video', 'vote_average',
       'vote_count'],
      dtype='object')

In [9]:
df.sample(3)

,adult,backdrop_path,genre_ids,id,title,original_language,original_title,overview,popularity,poster_path,release_date,softcore,video,vote_average,vote_count
15,False,/gyaBJn7eR8Ol205wmT2Xpi6IuhA.jpg,"[28, 35, 80]",11517,Money Train,en,Money Train,When a vengeful New York transit cop decides t...,8.4706,/jWBDz6Mf9aQVBiUS76JQsEhvoJl.jpg,1995-11-21,False,False,5.872,895
11,False,/nGYncNCfeAccyhhdGRgj3sbexPn.jpg,"[27, 9648]",334536,The Blackcoat's Daughter,en,The Blackcoat's Daughter,Two young women at a prestigious prep school a...,3.9767,/jO2aHAiWgQSlpAIPGZikiMDdMXx.jpg,2017-03-31,False,False,5.874,805
1,False,/3jiNJ4lyAmdSidvbFTFIL2GQGBu.jpg,"[35, 9648, 80, 12, 10751]",12096,The Pink Panther,en,The Pink Panther,When the coach of the France football team is ...,8.2298,/57ViRkdsddHLK32W8Nf3ZPLSAu4.jpg,2006-02-10,False,False,5.878,2201

In [10]:
df.columns

Index(['adult', 'backdrop_path', 'genre_ids', 'id', 'title',
       'original_language', 'original_title', 'overview', 'popularity',
       'poster_path', 'release_date', 'softcore', 'video', 'vote_average',
       'vote_count'],
      dtype='object')

In [11]:
df['adult'].value_counts()

adult
False    20
Name: count, dtype: int64

In [12]:
df["overview"][1]

'When the coach of the France football team is killed by a poisoned dart in the stadium at the end of a game, and his huge, expensive ring with the Pink Panther diamond  disappears, the ambitious Chief Inspector Dreyfus assigns the worst police inspector – Jacques Clouseau – to the case.'

In [13]:
df["overview"].isnull().sum()

np.int64(0)

In [14]:
df.head()

,adult,backdrop_path,genre_ids,id,title,original_language,original_title,overview,popularity,poster_path,release_date,softcore,video,vote_average,vote_count
0,False,/auBT5JgJEQjECGfC96JMmYQLpjK.jpg,[35],34803,Death at a Funeral,en,Death at a Funeral,Aaron's father's funeral is today at the famil...,5.0598,/oBCQYMJTqV3qLjrvZ5sTZUCBky7.jpg,2010-04-15,False,False,5.881,1099
1,False,/3jiNJ4lyAmdSidvbFTFIL2GQGBu.jpg,"[35, 9648, 80, 12, 10751]",12096,The Pink Panther,en,The Pink Panther,When the coach of the France football team is ...,8.2298,/57ViRkdsddHLK32W8Nf3ZPLSAu4.jpg,2006-02-10,False,False,5.878,2201
2,False,/sdirxnHDdRmrM55mWfLCFeMdRSn.jpg,[18],301502,Blonde,en,Blonde,"From her volatile childhood as Norma Jeane, th...",5.7435,/mEeHqtnWOR44vLCutEFku2WK6ou.jpg,2022-09-16,False,False,5.877,1565
3,False,/dnZdaGpQ36DlPkyr2bvaxPvc2OA.jpg,"[12, 16, 35, 10751, 10770]",13690,Open Season 2,en,Open Season 2,After falling head over hooves in love with Gi...,7.4210,/lM4bahouPblYcfngZtnNSkaWxCU.jpg,2008-09-24,False,False,5.877,1342
4,False,/fCdc3TZNNHGk1ZQBXENdWLqjUio.jpg,"[9648, 878, 53]",8836,The X-Files: I Want to Believe,en,The X-Files: I Want to Believe,Mulder and Scully are called back to duty by t...,7.4155,/3zQMhutUMJP6lK49x7i2YfsOHL9.jpg,2008-07-24,False,False,5.877,1720

In [15]:
import string
import re
def Lowercasing(text):
    results = ''
    for i in text :
        results = results + i.lower()
    return results

text_columns = ["title", "original_title", "overview"]

def rem_punctuation(text):
    exclude = string.punctuation
    return text.translate(str.maketrans('','',exclude))
def rem_special(text):

    text = re.sub(r"[^a-zA-Z\s]", '', text)

    return text
def rem_extra_space(text):
    text = re.sub(r"\s+", " ", text)
    return text

In [16]:
!pip install nltk

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: nltk in c:\users\lenovo\appdata\roaming\python\python310\site-packages (3.10.3)
Requirement already satisfied: defusedxml in c:\users\lenovo\appdata\roaming\python\python310\site-packages (from nltk) (0.7.1)
Requirement already satisfied: click in c:\users\lenovo\appdata\roaming\python\python310\site-packages (from nltk) (8.2.1)
Requirement already satisfied: joblib in c:\users\lenovo\appdata\roaming\python\python310\site-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in c:\users\lenovo\appdata\roaming\python\python310\site-packages (from nltk) (2026.2.28)
Requirement already satisfied: tqdm in c:\users\lenovo\appdata\roaming\python\python310\site-packages (from nltk) (4.67.3)
Requirement already satisfied: colorama in c:\users\lenovo\appdata\roaming\python\python310\site-packages (from click->nltk) (0.4.6)

[notice] A new release of pip is available: 24.3.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [17]:
import nltk

nltk.download("punkt")
nltk.download("punkt_tab")
from nltk.tokenize import word_tokenize

def apply_tokenization(text):
    tokens = word_tokenize(text)
    return tokens

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Lenovo\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\Lenovo\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

In [18]:
import nltk

nltk.download("stopwords")
from nltk.corpus import stopwords

stop_words = set(stopwords.words("english"))

def remove_stopwords(tokens):
    result = []

    for word in tokens:
        if word not in stop_words:
            result.append(word)

    return result

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Lenovo\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [19]:
from nltk.stem import WordNetLemmatizer
import nltk

nltk.download("wordnet")
nltk.download("omw-1.4")
lemmatizer = WordNetLemmatizer()

def lemmatize_tokens(tokens):
    result = []

    for word in tokens:
        result.append(lemmatizer.lemmatize(word))

    return result

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Lenovo\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\Lenovo\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

In [20]:
from sklearn.feature_extraction.text import TfidfVectorizer


def apply_tfidf(texts):
    tfidf = TfidfVectorizer()
    tfidf_matrix = tfidf.fit_transform(texts)

    return tfidf, tfidf_matrix

from sklearn.metrics.pairwise import cosine_similarity

def apply_similarity(tfidf_matrix):
    similarity_matrix = cosine_similarity(tfidf_matrix)

    return similarity_matrix

In [21]:
def join_tokens(tokens):
    return " ".join(tokens)

In [22]:
df["overview"] = df["overview"].apply(rem_punctuation)
df["overview"] = df["overview"].apply(Lowercasing)
df["overview"] = df["overview"].apply(rem_special)
df["overview"] = df["overview"].apply(rem_extra_space)
df["overview"] = df["overview"].apply(apply_tokenization)
df["overview"] = df["overview"].apply(remove_stopwords)
df["overview"] = df["overview"].apply(lemmatize_tokens)
df["overview"] = df["overview"].apply(join_tokens)

In [25]:
tfidf, tfidf_matrix = apply_tfidf(df["overview"])

In [26]:
similarity_matrix = apply_similarity(tfidf_matrix)

In [ ]:
similarity_matrix.shape

(20, 20)

In [27]:
similarity_matrix

array([[1.        , 0.        , 0.        , 0.        , 0.        ,
        0.02842645, 0.        , 0.01822291, 0.        , 0.01438763,
        0.        , 0.        , 0.        , 0.        , 0.05063148,
        0.04488489, 0.01001614, 0.        , 0.0672351 , 0.0170407 ],
       [0.        , 1.        , 0.        , 0.        , 0.        ,
        0.        , 0.02576685, 0.04486196, 0.        , 0.02069268,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.06324994, 0.        , 0.        , 0.01433201],
       [0.        , 0.        , 1.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 1.        , 0.03846369,
        0.        , 0.03796043, 0.        , 0.02843176, 0.06792547,
        0.        , 0.        , 0.        , 0.0983786 , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.03846369, 1.        ,
        0.        , 0.        , 0.        , 0.        , 0.03462241,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.02960213, 0.        , 0.        , 0.        ],
       [0.02842645, 0.        , 0.        , 0.        , 0.        ,
        1.        , 0.        , 0.        , 0.        , 0.        ,
        0.02276071, 0.        , 0.03628539, 0.02289167, 0.06565288,
        0.03016503, 0.        , 0.        , 0.03965595, 0.02609073],
       [0.        , 0.02576685, 0.        , 0.03796043, 0.        ,
        0.        , 1.        , 0.        , 0.02594777, 0.02867352,
        0.        , 0.04469189, 0.        , 0.04948863, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.01985964],
       [0.01822291, 0.04486196, 0.        , 0.        , 0.        ,
        0.        , 0.        , 1.        , 0.        , 0.02496135,
        0.02456028, 0.        , 0.03915428, 0.        , 0.        ,
        0.02650311, 0.02602218, 0.02258591, 0.        , 0.01728854],
       [0.        , 0.        , 0.        , 0.02843176, 0.        ,
        0.        , 0.02594777, 0.        , 1.        , 0.        ,
        0.        , 0.02725504, 0.        , 0.        , 0.01607858,
        0.        , 0.07126581, 0.        , 0.02122223, 0.        ],
       [0.01438763, 0.02069268, 0.        , 0.06792547, 0.03462241,
        0.        , 0.02867352, 0.02496135, 0.        , 1.        ,
        0.        , 0.        , 0.        , 0.        , 0.03041317,
        0.02569938, 0.01371989, 0.        , 0.        , 0.03929073],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.02276071, 0.        , 0.02456028, 0.        , 0.        ,
        1.        , 0.        , 0.        , 0.04802647, 0.0511723 ,
        0.        , 0.02308468, 0.04391302, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.04469189, 0.        , 0.02725504, 0.        ,
        0.        , 1.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.04489253, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.03628539, 0.        , 0.03915428, 0.        , 0.        ,
        0.        , 0.        , 1.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.03661415],
       [0.        , 0.        , 0.        , 0.0983786 , 0.        ,
        0.02289167, 0.04948863, 0.        , 0.        , 0.        ,
        0.04802647, 0.        , 0.        , 1.        , 0.05146675,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.05063148, 0.        , 0.        , 0.        , 0.        ,
        0.06565288, 0.        , 0.        , 0.01607858, 0.03041317,
        0.0511723 , 0.        , 0.        , 0.05146675, 1.        ,
        0.06726942, 0.06875546, 0.        , 0.06122236, 0.03267545],
       [0.04488489, 0.        , 0.        , 0.        , 0.        ,
        0.03016503, 0.        , 0.02650311, 0.        , 0.02569938,
        0.        , 0.        , 0.        , 0.        , 0.06726942,
        1.        , 0.04280175, 0.        , 0.        , 0.        ],
       [0.01001614, 0.06324994, 0.        , 0.        , 0.02960213,
        0.        , 0.        , 0.02602218, 0.07126581, 0.01371989,
        0.02308468, 0.        , 0.        , 0.        , 0.06875546,
        0.04280175, 1.        , 0.05229878, 0.03891073, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.02258591, 0.        , 0.        ,
        0.04391302, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.05229878, 1.        , 0.        , 0.03091137],
       [0.0672351 , 0.        , 0.        , 0.        , 0.        ,
        0.03965595, 0.        , 0.        , 0.02122223, 0.        ,
        0.        , 0.04489253, 0.        , 0.        , 0.06122236,
        0.        , 0.03891073, 0.        , 1.        , 0.        ],
       [0.0170407 , 0.01433201, 0.        , 0.        , 0.        ,
        0.02609073, 0.01985964, 0.01728854, 0.        , 0.03929073,
        0.        , 0.        , 0.03661415, 0.        , 0.03267545,
        0.        , 0.        , 0.03091137, 0.        , 1.        ]])

In [28]:
def recommend(movie):

    matches = df[df["title"].str.lower() == movie.lower()]

    if matches.empty:
        print("Movie not found")
        return

    index = matches.index[0]

    similarity_scores = list(enumerate(similarity_matrix[index]))

    similarity_scores = sorted(
        similarity_scores,
        key=lambda x: x[1],
        reverse=True
    )

    print(f"\nRecommendations for: {movie}\n")

    for i, score in similarity_scores[1:6]:
        print(df.iloc[i]["title"])

In [29]:
recommend('The Pink Panther')

Recommendations for: The Pink Panther

Beverly Hills Cop III
Line of Duty
Kung Fu Yoga
Mystery Men
Death Race: Inferno

In [30]:
print(df["title"].head(20).to_list())

['Death at a Funeral', 'The Pink Panther', 'Blonde', 'Open Season 2', 'The X-Files: I Want to Believe', 'Cold Pursuit', 'Kung Fu Yoga', 'Line of Duty', 'Futureworld', 'Mystery Men', 'Red Dot', "The Blackcoat's Daughter", 'Hard Rain', 'The Grandmother', 'The Cobbler', 'Money Train', 'Beverly Hills Cop III', 'Batman Ninja', 'It Comes at Night', 'Death Race: Inferno']

In [31]:
import joblib

# Save processed movie dataframe
df.to_pickle("movies.pkl")

# Save TF-IDF matrix
joblib.dump(tfidf_matrix, "tfidf_matrix.pkl")

# Save similarity matrix
joblib.dump(similarity_matrix, "similarity_matrix.pkl")

['similarity_matrix.pkl']

In [32]:
import streamlit as st
import pandas as pd
import joblib

df = pd.read_pickle("movies.pkl")
similarity_matrix = joblib.load("similarity_matrix.pkl")

st.title("🎬 Movie Recommendation System")

movie = st.selectbox(
    "Select a movie",
    df["title"].values
)

if st.button("Recommend"):

    index = df[df["title"] == movie].index[0]

    similarity_scores = list(
        enumerate(similarity_matrix[index])
    )

    similarity_scores = sorted(
        similarity_scores,
        key=lambda x: x[1],
        reverse=True
    )

    st.subheader("Recommended Movies")

    for i, score in similarity_scores[1:6]:
        st.write(df.iloc[i]["title"])

2026-09-14 19:37:26.094 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-14 19:37:26.367
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run C:\Users\Lenovo\AppData\Roaming\Python\Python310\site-packages\ipykernel_launcher.py [ARGUMENTS]
2026-09-14 19:37:26.367 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-14 19:37:26.367 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-14 19:37:26.367 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-14 19:37:26.367 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-14 19:37:26.387 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-14 19:37:26.396 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-14 19:37:26.397 Session state does not function when running a script without `streamlit run`
2026-09-14 19:37:26.397 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-14 19:37:26.397 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-14 19:37:26.403 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-14 19:37:26.409 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-14 19:37:26.409 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-14 19:37:26.409 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-14 19:37:26.420 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-14 19:37:26.425 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-14 19:37:26.425 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.